<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.551">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Stat 24320 - Problem 1 Modeling with Directed Graphs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../comments.css">
</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Problem 1 Modeling with Directed Graphs</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div id="3a34b9dc" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sympy <span class="im">as</span> sp</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy <span class="im">as</span> sci</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> PIL <span class="im">import</span> Image <span class="im">as</span> im</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.linalg <span class="im">import</span> svd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We first construct the digraph</p>
<div id="58a2300b" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a directed graph</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> nx.DiGraph()</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add nodes</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>G.add_nodes_from([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>])</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add vertices</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>edges <span class="op">=</span> [(<span class="dv">1</span>,<span class="dv">2</span>),(<span class="dv">2</span>,<span class="dv">3</span>),(<span class="dv">3</span>,<span class="dv">4</span>),(<span class="dv">4</span>,<span class="dv">2</span>),(<span class="dv">1</span>,<span class="dv">4</span>),(<span class="dv">3</span>,<span class="dv">1</span>),(<span class="dv">3</span>,<span class="dv">6</span>),(<span class="dv">6</span>,<span class="dv">3</span>),(<span class="dv">4</span>,<span class="dv">5</span>),(<span class="dv">5</span>,<span class="dv">6</span>)]</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>G.add_edges_from(edges)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw the graph</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>nx.draw_circular(G, with_labels<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-3-output-1.png" width="691" height="499" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We use networkx to determine the incidence matrix of the graph. Each row represents a node, each column represents an edge, with a -1 corresponding to the tail of an edge and a 1 representing the head.</p>
<div id="73a15012" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>inc_sparse <span class="op">=</span> <span class="op">-</span>nx.incidence_matrix(G, oriented<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> sp.Matrix(inc_sparse.toarray())</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>A</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="65">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}1.0 &amp; 1.0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\-1.0 &amp; 0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; -1.0 &amp; 1.0 &amp; 1.0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0 &amp; -1.0\\0 &amp; -1.0 &amp; 0 &amp; -1.0 &amp; 0 &amp; 0 &amp; 1.0 &amp; 1.0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 1.0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 1.0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>We then determine the nullspace of A and find a basis.</p>
<div id="8e10d9ff" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="bu">iter</span> <span class="op">=</span> A.nullspace()</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>basis <span class="op">=</span> <span class="bu">iter</span>[<span class="dv">0</span>]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> vec <span class="kw">in</span> <span class="bu">iter</span>[<span class="dv">1</span>:]:</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  basis <span class="op">=</span> basis.row_join(vec)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>basis</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="66">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}1.0 &amp; 1.0 &amp; -1.0 &amp; -1.0 &amp; 0\\-1.0 &amp; 0 &amp; 1.0 &amp; 1.0 &amp; 0\\1.0 &amp; 1.0 &amp; 0 &amp; -1.0 &amp; 0\\1 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 1 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 1.0\\0 &amp; 0 &amp; 1 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 1.0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 1 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 0 &amp; 1\end{matrix}\right]\)</span></p>
</div>
</div>
<p>As evident from our basis, there are two directed loops: column 2 and column 5. Moreover, we can construct more loops using linear combinations. Specifically, col1 + col3, col2 + col4 + col 5, and col2 + col3</p>
<div id="42f12f75" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dir_basis <span class="op">=</span> (basis.col(<span class="dv">1</span>)).row_join(basis.col(<span class="dv">4</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dir_basis <span class="op">=</span> dir_basis.row_join(basis.col(<span class="dv">0</span>) <span class="op">+</span> basis.col(<span class="dv">2</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>dir_basis <span class="op">=</span> dir_basis.row_join(basis.col(<span class="dv">1</span>) <span class="op">+</span> basis.col(<span class="dv">3</span>) <span class="op">+</span> basis.col(<span class="dv">4</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>dir_basis <span class="op">=</span> dir_basis.row_join(basis.col(<span class="dv">1</span>) <span class="op">+</span> basis.col(<span class="dv">2</span>))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>dir_basis</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="67">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}1.0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 1.0 &amp; 1.0\\1.0 &amp; 0 &amp; 1.0 &amp; 0 &amp; 1.0\\0 &amp; 0 &amp; 1 &amp; 0 &amp; 0\\1 &amp; 0 &amp; 0 &amp; 1 &amp; 1\\0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 1 &amp; 0 &amp; 1\\0 &amp; 0 &amp; 0 &amp; 1.0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 1 &amp; 0\\0 &amp; 1 &amp; 0 &amp; 1 &amp; 0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>We can visually confirm the nodes in these loops. Columns:</p>
<ol type="1">
<li>1, 2, 3</li>
<li>3, 6</li>
<li>2, 3, 4</li>
<li>1, 4, 5, 6, 3</li>
<li>3, 4, 5, 6</li>
</ol>
<section id="problem-1.1" class="level1">
<h1><em>Problem 1.1</em></h1>
<p>We are looking for Ax = b such that A represents a matrix where the rows are edges and columns represent whether a node is a head or tail for that edge (-1 for tail, +1 for head). x is some distribution of potential value on the nodes and b is the resulting potential differences of our edges. We know that for y in N(AT), yT*b = 0. We first construct A</p>
<div id="c8cf8627" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.zeros((<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>i <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> tail, head <span class="kw">in</span> edges:</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  A[i, tail<span class="op">-</span><span class="dv">1</span>] <span class="op">=</span> <span class="op">-</span><span class="dv">1</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  A[i, head<span class="op">-</span><span class="dv">1</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  i<span class="op">+=</span><span class="dv">1</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> sp.Matrix(A)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>A</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="68">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}-1.0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; -1.0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; -1.0 &amp; 1.0 &amp; 0 &amp; 0\\0 &amp; 1.0 &amp; 0 &amp; -1.0 &amp; 0 &amp; 0\\-1.0 &amp; 0 &amp; 0 &amp; 1.0 &amp; 0 &amp; 0\\1.0 &amp; 0 &amp; -1.0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; -1.0 &amp; 0 &amp; 0 &amp; 1.0\\0 &amp; 0 &amp; 1.0 &amp; 0 &amp; 0 &amp; -1.0\\0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 1.0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 1.0\end{matrix}\right]\)</span></p>
</div>
</div>
<div class="comments">
<p>Networkx has an “incidence_matrix” function that will do this… <code>nx.incidence_matrix(G).toarray()</code></p>
</div>
<div id="d110ad2f" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>A.T</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="69">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}-1.0 &amp; 0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\1.0 &amp; -1.0 &amp; 0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 1.0 &amp; -1.0 &amp; 0 &amp; 0 &amp; -1.0 &amp; -1.0 &amp; 1.0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 1.0 &amp; -1.0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1.0 &amp; -1.0\\0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1.0 &amp; -1.0 &amp; 0 &amp; 1.0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>Now we solve for y in N(AT). AT is a matrix where rows represent nodes and columns represent whether an edge is outgoing (-1) or incoming (+1) into the node, 0 if no connection to the node. Thus, solving the nullspace of AT gives us a basis for a vector with components representing the distribution of potential differences on the edges of our graph</p>
<div id="8d5cbe99" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>AT_null <span class="op">=</span> (A.T).nullspace()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>AT_null</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="70">
<pre><code>[Matrix([
 [  0],
 [1.0],
 [1.0],
 [  1],
 [  0],
 [  0],
 [  0],
 [  0],
 [  0],
 [  0]]),
 Matrix([
 [-1.0],
 [-1.0],
 [-1.0],
 [   0],
 [   1],
 [   0],
 [   0],
 [   0],
 [   0],
 [   0]]),
 Matrix([
 [1.0],
 [1.0],
 [  0],
 [  0],
 [  0],
 [  1],
 [  0],
 [  0],
 [  0],
 [  0]]),
 Matrix([
 [  0],
 [  0],
 [  0],
 [  0],
 [  0],
 [  0],
 [1.0],
 [  1],
 [  0],
 [  0]]),
 Matrix([
 [   0],
 [   0],
 [ 1.0],
 [   0],
 [   0],
 [   0],
 [-1.0],
 [   0],
 [ 1.0],
 [   1]])]</code></pre>
</div>
</div>
<p>We now construct our basis.</p>
<div id="5dfce33f" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>null_basis <span class="op">=</span> AT_null[<span class="dv">0</span>].T</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> vec <span class="kw">in</span> AT_null[<span class="dv">1</span>:]:</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  null_basis <span class="op">=</span> null_basis.col_join(vec.T)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>null_basis</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="71">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0 &amp; 1.0 &amp; 1.0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\-1.0 &amp; -1.0 &amp; -1.0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\1.0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1.0 &amp; 1 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 1.0 &amp; 0 &amp; 0 &amp; 0 &amp; -1.0 &amp; 0 &amp; 1.0 &amp; 1\end{matrix}\right]\)</span></p>
</div>
</div>
<p>We know that our null basis is composed of yT vectors for y in N(AT). Thus, we know that null_basis * b = 0, meaning if we solve for the null space of matrix we are given potential values of b.</p>
<div id="2085d97c" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>null_basis.nullspace()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="72">
<pre><code>[Matrix([
 [ 1.0],
 [-1.0],
 [   0],
 [   1],
 [   0],
 [   0],
 [   0],
 [   0],
 [   0],
 [   0]]),
 Matrix([
 [-1.0],
 [   0],
 [   0],
 [   0],
 [-1.0],
 [   1],
 [   0],
 [   0],
 [   0],
 [   0]]),
 Matrix([
 [-1.0],
 [ 1.0],
 [-1.0],
 [   0],
 [-1.0],
 [   0],
 [-1.0],
 [   1],
 [   0],
 [   0]]),
 Matrix([
 [-1.0],
 [ 1.0],
 [-1.0],
 [   0],
 [-1.0],
 [   0],
 [   0],
 [   0],
 [   1],
 [   0]]),
 Matrix([
 [-1.0],
 [ 1.0],
 [-1.0],
 [   0],
 [-1.0],
 [   0],
 [   0],
 [   0],
 [   0],
 [   1]])]</code></pre>
</div>
</div>
<p>Thus, we know that b must be some linear combination of these vectors. Moreover, we know that since a vector yT in null_basis represents a loop of the matrix, solving b in yT * b = 0 gives us a vector that will distribute potential differences along edges of the graph such that potential differences between loops will be 0.</p>
<div class="comments">
<p>I think your logic here isn’t quite clear. It should go something like this:</p>
<ol type="1">
<li>The valid values for <span class="math inline">\(b\)</span> are those which can be written as <span class="math inline">\(Ax=b\)</span> for some <span class="math inline">\(x\)</span>. That is, <span class="math inline">\(b\)</span> must be in the <strong>column space</strong> of <span class="math inline">\(A\)</span>.</li>
<li>Separately, we know a subset of edgesform a loop in the graph iff the sum of the rows in A corresponding to this subset sums to 0. If <span class="math inline">\(y\)</span> is a column vector with 1s for each edge in the subset, and 0s elsewhere, then the sum of the corresponding rows is <span class="math inline">\(y^T A\)</span>. Since we want this sum to be zero, we have <span class="math inline">\(y^T A = 0\)</span> and therefore <span class="math inline">\(A^T y=0\)</span> so we conclude that if <span class="math inline">\(y\)</span> is a subset of edges representing a loop, <span class="math inline">\(y\)</span> must be in the <strong>nullspace</strong> of <span class="math inline">\(A^T\)</span>.</li>
</ol>
<p>Putting these two together, we can use matrix algebra to show that if <span class="math inline">\(y\)</span> is in the nullspace of <span class="math inline">\(A^T\)</span> and <span class="math inline">\(b\)</span> is in the column space of <span class="math inline">\(A\)</span>, then <span class="math inline">\(y^T b = 0\)</span>.</p>
<p>That means that for any valid set of potential differences (<span class="math inline">\(b\)</span>), and any set of edges that form a loop (<span class="math inline">\(y\)</span>), the potential differences along the edges of the loop, as given by <span class="math inline">\(y^T b\)</span>, will be zero.</p>
<p>So we don’t use this to <em>find</em> <span class="math inline">\(b\)</span>, but rather to show that Kirchoff’s law is satisfied for any valid <span class="math inline">\(b\)</span>.</p>
<p>(It should be valid to do it the way you have done it, because the left nullspace of <span class="math inline">\(A\)</span> is the orthogonal complement of the column space of <span class="math inline">\(A\)</span>, but I think it’s clearer to think about it the way I just described.)</p>
</div>
</section>
<section id="problem-1.2" class="level1">
<h1><em>Problem 1.2</em></h1>
<p>We consider an incoming edge to all outgoing edges of a node. Thus, we can describe each node as an equation, using edge labels 1-10 as seen from our edge list. Node 1: e6 = e1 + e4 &lt;-&gt; e6 - e1 - e4 = 0, Node 2: e1 + e4 = e2 &lt;-&gt; e1 + e4 - e2 = 0. We follow this pattern for each edge, giving us a 6x10 matrix.</p>
<div id="92d62950" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># im.open('/content/drive/MyDrive/24320 - Linear Algebra Applications/24320_datasets/24320_graph_crop 2024-05-05 03_38_02.jpg')</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="6faec6a8" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>cur_mat <span class="op">=</span> sp.Matrix([</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>],</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>],</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>],</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span> ,<span class="dv">0</span>, <span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>],</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>],</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>cur_mat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="74">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}-1 &amp; 0 &amp; 0 &amp; 0 &amp; -1 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\1 &amp; -1 &amp; 0 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\0 &amp; 1 &amp; -1 &amp; 0 &amp; 0 &amp; -1 &amp; -1 &amp; 1 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 1 &amp; -1 &amp; 1 &amp; 0 &amp; 0 &amp; 0 &amp; -1 &amp; 0\\0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; -1\\0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 1 &amp; -1 &amp; 0 &amp; 1\end{matrix}\right]\)</span></p>
</div>
</div>
<p>As shown, we now have a matrix condition that must be satisfied, such that net total current in and out of each node is 0. To find this, we can solve for the nullspace of the system. This nullspace will form a basis for a vector distribution of currents. However, it will include -1 components that indicate a vector being “flipped.” Thus, we will use vector combinations that result in positive components only. Moreover, if a component is 0, that indicates that no flow is going through that edge.</p>
<div id="86eb2921" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>null_basis <span class="op">=</span> cur_mat.nullspace()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>null_basis</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="75">
<pre><code>[Matrix([
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0]]),
 Matrix([
 [-1],
 [-1],
 [-1],
 [ 0],
 [ 1],
 [ 0],
 [ 0],
 [ 0],
 [ 0],
 [ 0]]),
 Matrix([
 [1],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [0]]),
 Matrix([
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [1],
 [0],
 [0]]),
 Matrix([
 [ 0],
 [ 0],
 [ 1],
 [ 0],
 [ 0],
 [ 0],
 [-1],
 [ 0],
 [ 1],
 [ 1]])]</code></pre>
</div>
</div>
<p>We demonstrate that a linear combination of these vectors satsifies our conditions</p>
<div id="7c682543" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>test_vec <span class="op">=</span> null_basis[<span class="dv">0</span>]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> vec <span class="kw">in</span> null_basis[<span class="dv">1</span>:]:</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  test_vec <span class="op">+=</span> vec</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>test_vec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="76">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0\\1\\1\\1\\1\\1\\0\\1\\1\\1\end{matrix}\right]\)</span></p>
</div>
</div>
<div id="996b6ea0" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>cur_mat <span class="op">*</span> test_vec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="77">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0\\0\\0\\0\\0\\0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>Thus, we can see that we have found a basis for potential current distributions for our matrix.</p>
<div class="comments">
<p>To be precise, what you have demonstrated with code is that one specific vector in the span of the null_basis is a valid current distribution. You have not shown that all vectors in the span of the null_basis are valid current distributions. (Although it is <strong>true</strong>; that’s from the definition of the nullspace.)</p>
<p>To show this using code, you could do something like this, to make a generic sum:</p>
<div id="fb0c3759" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>syms <span class="op">=</span> sp.symbols(<span class="st">'x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11'</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>test_vec <span class="op">=</span> <span class="dv">0</span><span class="op">*</span>null_basis[<span class="dv">0</span>]</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(null_basis)):</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(i)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  test_vec <span class="op">+=</span> null_basis[i]<span class="op">*</span>syms[i]</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>display(test_vec)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>display(cur_mat<span class="op">*</span>test_vec)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0
1
2
3
4</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}- x_{2} + x_{3}\\x_{1} - x_{2} + x_{3}\\x_{1} - x_{2} + x_{5}\\x_{1}\\x_{2}\\x_{3}\\x_{4} - x_{5}\\x_{4}\\x_{5}\\x_{5}\end{matrix}\right]\)</span></p>
</div>
<div class="cell-output cell-output-display cell-output-markdown">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0\\0\\0\\0\\0\\0\end{matrix}\right]\)</span></p>
</div>
</div>
</div>
<p>#Problem 1.3: When examining the basis of directed loops, you can take a sum of all the columns in the basis. This will give you a vector along with components indicating how many times an edge is used in a loop of the graph. We can then compare this sum vector to our edges. If a coefficient for an edge is non-zero, that indicates that both ends of the edge, or the nodes, must be contained in our sum loop such that they are connected to every other node in the loop. Otherwise, if a node is not contained, then it is not connected. I will demonstrate an example below.</p>
<div id="4c9b7211" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sum_vec <span class="op">=</span> dir_basis.col(<span class="dv">0</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, dir_basis.cols):</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  sum_vec <span class="op">+=</span> dir_basis.col(i)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>sum_vec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="79">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}1.0\\2.0\\3.0\\1\\3\\1.0\\2\\1.0\\1\\2\end{matrix}\right]\)</span></p>
</div>
</div>
<p>Thus, we can see that all nodes have bidirectional communication, as every edge is utilized in our basis. This can be further confirmed by analyzing our graph: we can draw a path 1, 2, 3, 4, 5, 6, 3, 1, such that every node can reach another node in our path.</p>
<div class="comments">
<p>Would this approach work though if you had some disconnected loops? For example, suppose that nodes 5 and 6 only connected to each other. Or, for that matter, suppose that node 4 linked to node 5, but then 5 and 6 only link to each other.</p>
</div>
<div class="comments">
<p>This problem is generally done at an “M” level. However, I will give it an “R” because I’d really like to see you fix the issue I mentioned just above, about the disconnected loops.</p>
<p>If you address that, I will give it an “M” level. If you also have time to address the other points, I will give it an “E”.</p>
<p>Grade: R</p>
</div>
</section>
<section id="problem-2-image-compression-and-edge-detection" class="level1">
<h1><em>Problem 2: Image Compression and Edge Detection</em></h1>
<p>In this problem, we will be attempting to compress an image using a Haar Wavelet Transform</p>
<p>haar_wavelet: Creates an n-dimension Haar Wavelet transformation matrix.</p>
<div id="db93ab80" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> haar_wavelet(dim):</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  result <span class="op">=</span> <span class="dv">0</span><span class="op">*</span>np.identity(dim)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  jump <span class="op">=</span> dim<span class="op">//</span><span class="dv">2</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  i <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, dim, <span class="dv">2</span>):</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    result[i][j] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    result[i][j<span class="op">+</span><span class="dv">1</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    result[i<span class="op">+</span>jump][j] <span class="op">=</span> <span class="op">-</span><span class="dv">1</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    result[i<span class="op">+</span>jump][j<span class="op">+</span><span class="dv">1</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    i<span class="op">+=</span><span class="dv">1</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> ((<span class="dv">2</span><span class="op">**</span><span class="fl">0.5</span>)<span class="op">/</span><span class="dv">2</span>)<span class="op">*</span>result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>haar_wavelet_transform: performs the haar wavelet transform on a matrix A given m-dimension and n-dimension haar wavelet matrices</p>
<div id="0191a6a8" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> haar_wavelet_transform(A, Hm, Hn):</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  mat <span class="op">=</span> np.copy(A)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  transpose <span class="op">=</span> Hn.transpose()</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> <span class="fl">0.5</span><span class="op">*</span>(np.matmul(np.matmul(Hm, mat), transpose))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>haar_wavelet_transform_reverse: Given a haar_wavelet transform C, converts the trasnformation back to its original image</p>
<div id="d9b779a4" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> haar_wavelet_transform_reverse(C, Hm, Hn):</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  mat <span class="op">=</span> np.copy(C)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  transpose <span class="op">=</span> Hm.transpose()</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> <span class="dv">2</span><span class="op">*</span>np.matmul(np.matmul(transpose, mat), Hn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>edge_transform: performs the edge transform on an already transformed haar_wavelet image to obtain the edge image</p>
<div id="13c2794a" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> edge_transform(transform, Hm, Hn):</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  zerod <span class="op">=</span> np.copy(transform)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  rows <span class="op">=</span> Hm.shape[<span class="dv">0</span>]<span class="op">//</span><span class="dv">2</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  cols <span class="op">=</span> Hn.shape[<span class="dv">0</span>]<span class="op">//</span><span class="dv">2</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> col <span class="kw">in</span> <span class="bu">range</span>(cols):</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> row <span class="kw">in</span> <span class="bu">range</span>(rows):</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>      zerod[row][col] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  transpose <span class="op">=</span> Hm.transpose()</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> <span class="dv">2</span> <span class="op">*</span> np.matmul(np.matmul(transpose, zerod), Hn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>stack: stacks a 2D matrix onto itself to give it a 3D shape such that there is a Red, Green, and Blue value for an RGB image reader. Sets type to uint8 to make it compatible with PIL.Image</p>
<div id="32d2e329" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> stack(matrix):</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> (np.stack([matrix, matrix, matrix], axis<span class="op">=</span><span class="dv">2</span>)).astype(np.uint8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>clean_matrix: ensures that the given matrix has an even number of rows and columns</p>
<div id="9602226e" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> clean_matrix(matrix):</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  rows, cols <span class="op">=</span> matrix.shape</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  result <span class="op">=</span> np.copy(matrix)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> rows <span class="op">%</span> <span class="dv">2</span> <span class="op">==</span> <span class="dv">0</span> <span class="kw">and</span> cols <span class="op">%</span> <span class="dv">2</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>      <span class="cf">return</span> result</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> rows <span class="op">%</span> <span class="dv">2</span> <span class="op">!=</span> <span class="dv">0</span>:</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>    result <span class="op">=</span> np.delete(result, <span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> cols <span class="op">%</span> <span class="dv">2</span> <span class="op">!=</span> <span class="dv">0</span>:</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    result <span class="op">=</span> np.delete(result, <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>blur: blurs a given array by a factor of 4</p>
<div id="8b2a8c79" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> blur(matrix):</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  cur <span class="op">=</span> clean_matrix(matrix)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  rows, cols <span class="op">=</span> cur.shape</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  hm <span class="op">=</span> haar_wavelet(rows)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  hn <span class="op">=</span> haar_wavelet(cols)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  transformation <span class="op">=</span> haar_wavelet_transform(cur, hm, hn)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  result <span class="op">=</span> np.copy(transformation[<span class="dv">0</span>:(rows<span class="op">//</span><span class="dv">2</span>), <span class="dv">0</span>:(cols<span class="op">//</span><span class="dv">2</span>)])</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> result</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="354e626f" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>haar_wavelet(<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="87">
<pre><code>array([[ 0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.70710678,  0.70710678],
       [-0.70710678,  0.70710678,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.70710678,  0.70710678]])</code></pre>
</div>
</div>
<div class="comments">
<p>I love how you’ve put all the above code into functions. Here, I’ve displayed the haar_wavelet visually (so I can see that it makes sense – which it does!):</p>
<div id="283d049a" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>plt.imshow(haar_wavelet(<span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-27-output-1.png" width="407" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="comments">
<p>Since I don’t have your image file, I am using a cat image instead.</p>
</div>
<div id="aabe17b9" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>image <span class="op">=</span> im.<span class="bu">open</span>(<span class="st">'catimage.png'</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>image</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="89">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-28-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We convert the image into a numpy array and then remove a row and/or column if there is an odd count of them. This is because the Haar Wavelet Matrix requires an even dimension as per definition.</p>
<div id="8bd85f08" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>image_arr <span class="op">=</span> np.asarray(image)[:,:,<span class="dv">0</span>]</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>working <span class="op">=</span> clean_matrix(image_arr)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>working</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="90">
<pre><code>array([[117, 117, 117, ..., 138, 140, 140],
       [117, 117, 117, ..., 138, 140, 140],
       [117, 117, 117, ..., 138, 140, 140],
       ...,
       [123, 123, 123, ..., 129, 130, 132],
       [123, 123, 123, ..., 129, 130, 132],
       [127, 127, 127, ..., 133, 134, 135]], dtype=uint8)</code></pre>
</div>
</div>
<p>Using the dimensions of the cleaned matrix, we construct the m-dimension and n-dimension haar wavelet matrices needed for the transformation.</p>
<div id="6ab2d984" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>haar_m <span class="op">=</span> haar_wavelet(working.shape[<span class="dv">0</span>])</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>haar_n <span class="op">=</span> haar_wavelet(working.shape[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We now perform the first iteration of the transformation.</p>
<div id="8d30d4c3" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>transform <span class="op">=</span> haar_wavelet_transform(working, haar_m, haar_n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="c402f8ee" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>stacked <span class="op">=</span> stack(transform)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>im.fromarray(stacked)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="93">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-32-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="comments">
<p>Wow, that’s seriously nice-looking! I’m impressed.</p>
</div>
<p>We can also find the edge-only version using our transformation</p>
<div id="918a662b" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>edges <span class="op">=</span> edge_transform(transform, haar_m, haar_n)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>stacked_edges <span class="op">=</span> stack(edges)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>im.fromarray(stacked_edges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="94">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-33-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can also convert the image back to its original state to demonstrate the compression value of this transformation.</p>
<div id="e29a171e" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>original <span class="op">=</span> haar_wavelet_transform_reverse(transform, haar_m, haar_n)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>stacked_original <span class="op">=</span> stack(original)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>im.fromarray(stacked_original)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="95">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-34-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can then begin the process of blurring the original image until it is unrecognizable. Although this can be done as a function, I believe it will help to see the step-by-step process.</p>
<p>continuous_blur: given an image, returns a list of blurred images of length step+1 starting with the original, with each subsequent item blurred 4x the previous.</p>
<div id="f13e890a" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> continuous_blur(image, steps):</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  blurs <span class="op">=</span> [image]</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  stacked_blurs <span class="op">=</span> [stack(image)]</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(steps):</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    next_blur <span class="op">=</span> blur(blurs[i])</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    blurs.append(next_blur)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>    stacked_blurs.append(stack(next_blur))</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> stacked_blurs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="9fce98d1" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>blurs <span class="op">=</span> continuous_blur(working, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="1ee66b15" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>im.fromarray(blurs[<span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="98">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-37-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="4712a69f" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>im.fromarray(blurs[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="99">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-38-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="1d8b3eeb" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>im.fromarray(blurs[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="100">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-39-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="ba296e32" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>im.fromarray(blurs[<span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="101">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-40-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="d5f3bc22" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>im.fromarray(blurs[<span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="102">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-41-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="9ded8ac0" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>im.fromarray(blurs[<span class="dv">5</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="103">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-42-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As shown by our constant image blurring, these images become so small that it is almost impossible to recognize their original form.</p>
<div class="comments">
<p>The images do become small – but also blurred. (With my cat in here, it’s hard to see the blur actually, but I think it is there.)</p>
</div>
</section>
<section id="problem-2-writeup" class="level1">
<h1><em>Problem 2 Writeup</em></h1>
<p>As demonstrated by the Haar Wavelet transformation, we have an effective method of image compression that is cheaper than storing the original image. This is because storing the edges of an image is cheaper than storing the actual image since we are only storing a fraction of the image’s data. Parts of the image’s data that are near-uniform in color are stored in the blurred image of the data. One way we can make this image compression more effective is by identifying the average pixel color of edges. Using that information from our edge images, we can then choose to 0 out pixel blocks below that average color value in the converted <strong>edges</strong> image. Given the original dimensions of the edge image to be M x N pixels, we can convert this approximation into a matrix A of size M’ x N’, where we choose a box of size P, such that M’ = M/P, N’ = N/P. Then for each element a_ji in this matrix, we can choose a_ji = 0 if that box of size PxP is a zeroed out area, otherwise we choose a_ji = 1 such that the information in this area must be preserved. We can then save all boxes set to 1 as respective to their element a_ji, representing a box in the original image of size [j<em>P:(j+1)</em>P] x [i<em>P: (i+1)</em>P], into a list B. This list B will contain all boxes of size P of image data that has been conserved. When we want to convert back to the matrix, we can first construct a matrix called <strong>final</strong> of size (M’* P) x (N’ * P). Then, we iterate through our matrix A. For each section of size PxP in <strong>final</strong>, we identify whether it should be represented by a zeroed entry (a_ji = 0) or a data entry (a_ji = 1). If it is represented by 0’s, we construct a box of zeros of size PxP and insert it into <strong>final</strong>. Otherwise, we take the current entry of B and insert that box of size PxP into the matrix. We then iterate B to the next entry in the list. We repeat this process until we have fully constructed the edge image with zeroed sections. We can then use this full constructed edge image as our approximation for all edges in the image. Since we know that both Wn and Wm are orthogonal, we can use the original equation that found our edge image: <strong>edges</strong> = 2* Wm.T * <strong>transform.z</strong> * Wn, where <strong>transform.z</strong> represents the Haar Wavelet Transform matrix with the blurred section zeroed out. Due to this formula, we know that <strong>transform.z</strong> = 0.5 * Wm * <strong>edges</strong> * Wn.T. Then we can reconstruct our original transform by replacing the zeroed out section of <strong>tranform.z</strong> with the pixel values from our blurred image. Thus, we have found a way to store the edges in a more compressed form than originally found by the Haar Wavelet Transform.</p>
<p>We can demonstrate this method through a simple 2x3 approximation of a 4x6 edge matrix. This assumes that P = 2</p>
<div id="a5678871" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># original matrix A:</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> sp.Matrix([</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">155</span>, <span class="dv">155</span>, <span class="dv">50</span>, <span class="dv">50</span>],</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">8</span>, <span class="dv">10</span>, <span class="dv">155</span>, <span class="dv">155</span>, <span class="dv">100</span>, <span class="dv">100</span>],</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">155</span>, <span class="dv">155</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">2</span>, <span class="dv">4</span>],</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">155</span>, <span class="dv">155</span>, <span class="dv">20</span>, <span class="dv">15</span>, <span class="dv">40</span>, <span class="dv">40</span>]</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>A</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="104">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}4 &amp; 2 &amp; 155 &amp; 155 &amp; 50 &amp; 50\\8 &amp; 10 &amp; 155 &amp; 155 &amp; 100 &amp; 100\\155 &amp; 155 &amp; 20 &amp; 25 &amp; 2 &amp; 4\\155 &amp; 155 &amp; 20 &amp; 15 &amp; 40 &amp; 40\end{matrix}\right]\)</span></p>
</div>
</div>
<p>We notice that our edge color seems to be 155. Thus, we choose to zero out all blocks that have pixel values less than our edge value.</p>
<div id="81625637" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>Az <span class="op">=</span> A[:, :]</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>size <span class="op">=</span> sp.shape(Az)[<span class="dv">0</span>] <span class="op">*</span> sp.shape(Az)[<span class="dv">1</span>]</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(size):</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> Az[i] <span class="op">&lt;</span> <span class="dv">155</span>:</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    Az[i] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>Az</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="105">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0 &amp; 0 &amp; 155 &amp; 155 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 155 &amp; 155 &amp; 0 &amp; 0\\155 &amp; 155 &amp; 0 &amp; 0 &amp; 0 &amp; 0\\155 &amp; 155 &amp; 0 &amp; 0 &amp; 0 &amp; 0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>We approximate this matrix by identifying data sections and zero sections</p>
<div id="e8c5a6b9" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>approx <span class="op">=</span> sp.Matrix([</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>],</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>]</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> [sp.Matrix([</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">155</span>, <span class="dv">155</span>],</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">155</span>, <span class="dv">155</span>]</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>]),</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  sp.Matrix([</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>      [<span class="dv">155</span>,<span class="dv">155</span>],</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>      [<span class="dv">155</span>,<span class="dv">155</span>]</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  ])]</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>sp.pprint(approx)</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>B</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>⎡0  1  0⎤
⎢       ⎥
⎣1  0  0⎦</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="106">
<pre><code>[Matrix([
 [155, 155],
 [155, 155]]),
 Matrix([
 [155, 155],
 [155, 155]])]</code></pre>
</div>
</div>
<p>As can be seen, our compression would allow us to recreate an image that could approximate the edges of a matrix and store it in as small as P^2 less area.</p>
<div class="comments">
<p>Hah I was just about to start writing a comment “but what about image compression?”, and then I saw this section. Very very well done!</p>
<p>Grade E</p>
</div>
</section>
<section id="problem-3-least-squares" class="level1">
<h1><em>Problem 3 Least Squares</em></h1>
<p>In this problem, we will attempt to predict the end results of the Ivy League football season using the midseason table. We first read in the midseason table of the Ivy League. Both rows and columns indicate teams. Given row index j, column index j, the element a[j][i] represents how many points team j scored against team i.</p>
<p>#Problem 3 Writeup</p>
<p>In this project, I attempt to use SVD to complete the matrix. First, I find the current leaders of the league using the power matrix influence. Then, I approximate the missing values of our matrix to be the average defensive performance a team of column index i has put on prior to the midseason review. Afterwards, I calculate the singular value decomposition and then choose k singular values, such that the remaining n-k singular values are much smaller than the ones I chose. This allows me to weight the “important” vectors of U and Vt (the ones with large singular values), more heavily, creating an approimate final table that is influenced by the results of the midterm review. Then, I compare it to the actual final table to see how the results differ.</p>
<p>The reason I chose to take their average defensive performance (e.g.&nbsp;the average score other teams put up against them) was because specifically in college football, standout players are often found on the offensive side, mainly quarterbacks. Because quarterbacks have a heavy influence on the game, they often are in control of how well an offense plays or not. If they’re in a slump, their team suffers, if they’re on fire, the team scores. However, a football team’s defense is often more consistent because their overall performance isn’t dependent on one player. Thus, the amount of point scored against a team will often be more consistent than the amount of points a team scores because the defensive side of the team is likely more consistent than the quarterback.</p>
<p>This solution is limited by the strength of schedule a team has before the midseason. If a team has a really easy schedule, such that they only play easy opponents before we take a look midway through the season, then they will look much better on paper than they may really be in the league. Because of that, I ran into issues where Cornell, which should not have been ranked number 1, was consistently ranked number 1 in my approximations due to their strong performance early on.</p>
</section>
<section id="problem-3-code" class="level1">
<h1><em>Problem 3 Code</em></h1>
<p>find_ranking_power_matrix: finds the ranking of teams using a power matrix given a weighted adjacency matrix</p>
<div id="f87f19a7" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> find_ranking_power_matrix(weight_adj):</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  weight_power <span class="op">=</span> weight_adj <span class="op">+</span> weight_adj<span class="op">**</span><span class="dv">2</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  weight_power_sum <span class="op">=</span> [<span class="bu">sum</span>(weight_power[i]) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">8</span>)]</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  rrank_weight <span class="op">=</span> np.argsort(weight_power_sum)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  rank_weight <span class="op">=</span> np.flip(rrank_weight)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> num <span class="kw">in</span> rank_weight:</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(teams[num]<span class="op">+</span><span class="st">'</span><span class="ch">\n</span><span class="st">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>weighted_adjacency_matrix: given a table of scores, finds the weighted adjacency matrix of the table</p>
<div id="28fa82b6" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> weighted_adjacency_matrix(table):</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  weighted_adjacency <span class="op">=</span> np.copy(table)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(rows):</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(cols):</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> weighted_adjacency[j][i] <span class="op">&gt;=</span> weighted_adjacency[i][j]:</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>        weighted_adjacency[j][i] <span class="op">=</span> weighted_adjacency[j][i] <span class="op">-</span> weighted_adjacency[i][j]</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>        weighted_adjacency[i][j] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>      <span class="cf">else</span>:</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>        weighted_adjacency[i][j] <span class="op">=</span> weighted_adjacency[i][j] <span class="op">-</span> weighted_adjacency[j][i]</span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>        weighted_adjacency[j][i] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">return</span> weighted_adjacency</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="1b74680a" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>midseason_view <span class="op">=</span> pd.read_csv(<span class="st">'Ivy League Stats - Midseason.csv'</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>midseason_view</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="109">
<div>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Unnamed: 0</th>
<th data-quarto-table-cell-role="th">Harvard</th>
<th data-quarto-table-cell-role="th">Yale</th>
<th data-quarto-table-cell-role="th">Dartmouth</th>
<th data-quarto-table-cell-role="th">Princeton</th>
<th data-quarto-table-cell-role="th">Penn</th>
<th data-quarto-table-cell-role="th">Brown</th>
<th data-quarto-table-cell-role="th">Cornell</th>
<th data-quarto-table-cell-role="th">Columbia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Harvard</td>
<td>0.0</td>
<td>NaN</td>
<td>NaN</td>
<td>14.0</td>
<td>NaN</td>
<td>34.0</td>
<td>41.0</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Yale</td>
<td>NaN</td>
<td>0.0</td>
<td>31.0</td>
<td>NaN</td>
<td>17.0</td>
<td>NaN</td>
<td>21.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Dartmouth</td>
<td>NaN</td>
<td>24.0</td>
<td>0.0</td>
<td>NaN</td>
<td>23.0</td>
<td>NaN</td>
<td>NaN</td>
<td>20.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Princeton</td>
<td>21.0</td>
<td>NaN</td>
<td>NaN</td>
<td>0.0</td>
<td>NaN</td>
<td>27.0</td>
<td>NaN</td>
<td>10.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Penn</td>
<td>NaN</td>
<td>27.0</td>
<td>20.0</td>
<td>NaN</td>
<td>0.0</td>
<td>NaN</td>
<td>NaN</td>
<td>20.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Brown</td>
<td>31.0</td>
<td>NaN</td>
<td>NaN</td>
<td>28.0</td>
<td>NaN</td>
<td>0.0</td>
<td>14.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>Cornell</td>
<td>23.0</td>
<td>23.0</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>36.0</td>
<td>0.0</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>Columbia</td>
<td>NaN</td>
<td>NaN</td>
<td>9.0</td>
<td>7.0</td>
<td>17.0</td>
<td>NaN</td>
<td>NaN</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
<p>We collect all the team names from this table.</p>
<div id="3ff7ff42" class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>teams <span class="op">=</span> <span class="bu">list</span>(midseason_view)[<span class="dv">1</span>:]</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>teams</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="110">
<pre><code>['Harvard',
 'Yale',
 'Dartmouth',
 'Princeton',
 'Penn',
 'Brown',
 'Cornell',
 'Columbia']</code></pre>
</div>
</div>
<p>However, since having team names will be messy for data analysis, we transform the dataframe into a numpy array and delete the row names.</p>
<div id="09b1d497" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>midseason <span class="op">=</span> midseason_view.to_numpy()</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>midseason</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="111">
<pre><code>array([['Harvard', 0.0, nan, nan, 14.0, nan, 34.0, 41.0, nan],
       ['Yale', nan, 0.0, 31.0, nan, 17.0, nan, 21.0, nan],
       ['Dartmouth', nan, 24.0, 0.0, nan, 23.0, nan, nan, 20.0],
       ['Princeton', 21.0, nan, nan, 0.0, nan, 27.0, nan, 10.0],
       ['Penn', nan, 27.0, 20.0, nan, 0.0, nan, nan, 20.0],
       ['Brown', 31.0, nan, nan, 28.0, nan, 0.0, 14.0, nan],
       ['Cornell', 23.0, 23.0, nan, nan, nan, 36.0, 0.0, nan],
       ['Columbia', nan, nan, 9.0, 7.0, 17.0, nan, nan, 0.0]],
      dtype=object)</code></pre>
</div>
</div>
<div id="ab870d36" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>midseason <span class="op">=</span> np.delete(midseason, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>sp.Matrix(midseason)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="112">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0 &amp; \text{NaN} &amp; \text{NaN} &amp; 14.0 &amp; \text{NaN} &amp; 34.0 &amp; 41.0 &amp; \text{NaN}\\\text{NaN} &amp; 0 &amp; 31.0 &amp; \text{NaN} &amp; 17.0 &amp; \text{NaN} &amp; 21.0 &amp; \text{NaN}\\\text{NaN} &amp; 24.0 &amp; 0 &amp; \text{NaN} &amp; 23.0 &amp; \text{NaN} &amp; \text{NaN} &amp; 20.0\\21.0 &amp; \text{NaN} &amp; \text{NaN} &amp; 0 &amp; \text{NaN} &amp; 27.0 &amp; \text{NaN} &amp; 10.0\\\text{NaN} &amp; 27.0 &amp; 20.0 &amp; \text{NaN} &amp; 0 &amp; \text{NaN} &amp; \text{NaN} &amp; 20.0\\31.0 &amp; \text{NaN} &amp; \text{NaN} &amp; 28.0 &amp; \text{NaN} &amp; 0 &amp; 14.0 &amp; \text{NaN}\\23.0 &amp; 23.0 &amp; \text{NaN} &amp; \text{NaN} &amp; \text{NaN} &amp; 36.0 &amp; 0 &amp; \text{NaN}\\\text{NaN} &amp; \text{NaN} &amp; 9.0 &amp; 7.0 &amp; 17.0 &amp; \text{NaN} &amp; \text{NaN} &amp; 0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>We notice that this graph can represent an adjacency matrix, with weights. To get to this point, we first zero out every nan value, such that we every nan represents a lack of an adjacency between the two teams.</p>
<div id="c4c148dc" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>rows, cols <span class="op">=</span> np.shape(midseason)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(rows):</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(cols):</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> midseason[j][i] <span class="op">&gt;=</span> <span class="dv">0</span>:</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>      midseason[j][i] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>midseason <span class="op">=</span> midseason.astype(<span class="st">'float'</span>)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>midseason</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="113">
<pre><code>array([[ 0.,  0.,  0., 14.,  0., 34., 41.,  0.],
       [ 0.,  0., 31.,  0., 17.,  0., 21.,  0.],
       [ 0., 24.,  0.,  0., 23.,  0.,  0., 20.],
       [21.,  0.,  0.,  0.,  0., 27.,  0., 10.],
       [ 0., 27., 20.,  0.,  0.,  0.,  0., 20.],
       [31.,  0.,  0., 28.,  0.,  0., 14.,  0.],
       [23., 23.,  0.,  0.,  0., 36.,  0.,  0.],
       [ 0.,  0.,  9.,  7., 17.,  0.,  0.,  0.]])</code></pre>
</div>
</div>
<p>We notice that it is similar to the weighted adjacency matrix from our last project. However, the key difference is that both teams have scores for a specific matchup. This can easily be fixed by subtracting the lower score from the higher score and zeroing out the low score. Thus we perform the following.</p>
<div id="e86ee0a9" class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>weighted_adjacency <span class="op">=</span> weighted_adjacency_matrix(midseason)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>weighted_adjacency</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="114">
<pre><code>array([[ 0.,  0.,  0.,  0.,  0.,  3., 18.,  0.],
       [ 0.,  0.,  7.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3.,  0.,  0., 11.],
       [ 7.,  0.,  0.,  0.,  0.,  0.,  0.,  3.],
       [ 0., 10.,  0.,  0.,  0.,  0.,  0.,  3.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0., 22.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])</code></pre>
</div>
</div>
<p>From this weighted adjacency, we can then find the power matrix so that we can rank the schools during midseason.</p>
<div id="2b5f2822" class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>find_ranking_power_matrix(weighted_adjacency)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cornell

Harvard

Dartmouth

Penn

Princeton

Yale

Brown

Columbia
</code></pre>
</div>
</div>
<p>As demonstrated by the power matrix, we can see that Cornell is currently the strongest school, followed by Harvard and Dartmouth. We will take this information into consideration as we perform SVD to find a matrix completion.</p>
<p>There are many ways to estimate a complete matrix. One way we can do this is by using the Singular Value Decomposition of a matrix and estimate the complete matrix by using k singular values. The choice of k can be decided by estimating how important each singular value is. The most important part, however, is what we choose to do with our missing values. In this case, I believe the best option is replace them with the average value in their respective column. That is to say, given a missing value for an element with row index j and column index i, we input the average points scored against team i as our replacement. The intuition behind this is that a team’s defense in football, especially in college, tends to be consistent, regardless of the teams they play. I will explain my reasoning in more depth in the write-up.</p>
<div id="ef3922fe" class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>midseason_svd <span class="op">=</span> np.copy(midseason)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(rows):</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(cols):</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> i <span class="op">!=</span> j <span class="kw">and</span> midseason[j][i] <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>      midseason_svd[j][i] <span class="op">=</span> np.mean(midseason[:, i])</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>midseason_svd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="116">
<pre><code>array([[ 0.   ,  9.25 ,  7.5  , 14.   ,  7.125, 34.   , 41.   ,  6.25 ],
       [ 9.375,  0.   , 31.   ,  6.125, 17.   , 12.125, 21.   ,  6.25 ],
       [ 9.375, 24.   ,  0.   ,  6.125, 23.   , 12.125,  9.5  , 20.   ],
       [21.   ,  9.25 ,  7.5  ,  0.   ,  7.125, 27.   ,  9.5  , 10.   ],
       [ 9.375, 27.   , 20.   ,  6.125,  0.   , 12.125,  9.5  , 20.   ],
       [31.   ,  9.25 ,  7.5  , 28.   ,  7.125,  0.   , 14.   ,  6.25 ],
       [23.   , 23.   ,  7.5  ,  6.125,  7.125, 36.   ,  0.   ,  6.25 ],
       [ 9.375,  9.25 ,  9.   ,  7.   , 17.   , 12.125,  9.5  ,  0.   ]])</code></pre>
</div>
</div>
<p>We then use scipy.linalg’s svd function to find the singular value decomposition of the matrix</p>
<div id="37c7e2d2" class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>U, S, Vt <span class="op">=</span> svd(midseason)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>S</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="117">
<pre><code>array([74.75657202, 53.98601884, 48.45216671, 37.35834194, 25.97844269,
       23.26194426, 14.72288866,  7.93382333])</code></pre>
</div>
</div>
<div id="d005e87d" class="cell" data-execution_count="56">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>plt.plot(S)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="tandocalec_files/figure-html/cell-57-output-1.png" width="566" height="411" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We see our sharpest decline in eigenvalue magnitude between 0 to 1. Afterwards, we have steady decline, but since 4 and 5 maintain similar values, we can choose an approximation to be k=5. Thus, we will perform a low rank approximation with k=2 for analysis and k=5 as our final</p>
<div id="adf6bf44" class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>final_approx_k2 <span class="op">=</span> np.<span class="bu">round</span>(np.matmul(np.matmul(U[:, :k], np.diag(S[:k])), Vt[:k, :]))</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>sp.Matrix(final_approx_k2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="119">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}21.0 &amp; 2.0 &amp; -1.0 &amp; 14.0 &amp; -2.0 &amp; 33.0 &amp; 23.0 &amp; -1.0\\4.0 &amp; 14.0 &amp; 9.0 &amp; 1.0 &amp; 8.0 &amp; 7.0 &amp; 4.0 &amp; 9.0\\1.0 &amp; 22.0 &amp; 15.0 &amp; -3.0 &amp; 14.0 &amp; 1.0 &amp; -1.0 &amp; 15.0\\12.0 &amp; 5.0 &amp; 2.0 &amp; 8.0 &amp; 1.0 &amp; 19.0 &amp; 13.0 &amp; 2.0\\1.0 &amp; 23.0 &amp; 16.0 &amp; -3.0 &amp; 15.0 &amp; 2.0 &amp; 0 &amp; 16.0\\12.0 &amp; 0 &amp; -1.0 &amp; 9.0 &amp; -2.0 &amp; 20.0 &amp; 14.0 &amp; -1.0\\16.0 &amp; 13.0 &amp; 7.0 &amp; 9.0 &amp; 5.0 &amp; 26.0 &amp; 17.0 &amp; 7.0\\1.0 &amp; 7.0 &amp; 5.0 &amp; 0 &amp; 4.0 &amp; 1.0 &amp; 0 &amp; 5.0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>As shown above, given k=2, we have a matrix approximation that is difficult to parse. This is because we have only selected the first two columns and rows of U and Vt respectively. This means that our matrix is the cross product of 4 corresponding vectors, which results in high variance and unpredictability, as small changes in either corresponding vectors results in large changes when you cross them. We can apply our power matrix summation (after zeroing out the i=j entries) to see which teams would win the league according to our prediction.</p>
<div id="2d4e1c33" class="cell" data-execution_count="58">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(np.shape(final_approx_k2)[<span class="dv">0</span>]):</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  final_approx_k2[i][i] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>k1_weight <span class="op">=</span> weighted_adjacency_matrix(final_approx_k2)</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>find_ranking_power_matrix(k1_weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Harvard

Penn

Cornell

Dartmouth

Princeton

Yale

Columbia

Brown
</code></pre>
</div>
</div>
<p>As predicted, this ranking resulted in multiple shifts due to the high unpredictability of using a low k value.</p>
<div id="abc2628a" class="cell" data-execution_count="59">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>final_approx_k5 <span class="op">=</span> np.<span class="bu">round</span>(np.matmul(np.matmul(U[:, :k], np.diag(S[:k])), Vt[:k, :]))</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>sp.Matrix(np.<span class="bu">round</span>(np.matmul(np.matmul(U[:, :k], np.diag(S[:k])), Vt[:k, :])))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="121">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}1.0 &amp; 0 &amp; -1.0 &amp; 13.0 &amp; 2.0 &amp; 34.0 &amp; 41.0 &amp; -1.0\\-1.0 &amp; 0 &amp; 32.0 &amp; 2.0 &amp; 15.0 &amp; 1.0 &amp; 20.0 &amp; 1.0\\-2.0 &amp; 27.0 &amp; 3.0 &amp; 3.0 &amp; 14.0 &amp; -1.0 &amp; 1.0 &amp; 20.0\\20.0 &amp; 8.0 &amp; 1.0 &amp; 2.0 &amp; -3.0 &amp; 25.0 &amp; 1.0 &amp; 1.0\\2.0 &amp; 24.0 &amp; 15.0 &amp; -3.0 &amp; 14.0 &amp; 2.0 &amp; -2.0 &amp; 16.0\\31.0 &amp; -1.0 &amp; -1.0 &amp; 28.0 &amp; 3.0 &amp; 1.0 &amp; 13.0 &amp; 0\\23.0 &amp; 19.0 &amp; 1.0 &amp; -1.0 &amp; -2.0 &amp; 36.0 &amp; 0 &amp; 7.0\\2.0 &amp; 3.0 &amp; 11.0 &amp; 4.0 &amp; 7.0 &amp; -4.0 &amp; 5.0 &amp; 3.0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>Meanwhile, when k=5, we see lower variance in terms of scores. We now see how our power-ranking looks according to this</p>
<div id="cffc2194" class="cell" data-execution_count="60">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(np.shape(final_approx_k5)[<span class="dv">0</span>]):</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  final_approx_k5[i][i] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>k6_weight <span class="op">=</span> weighted_adjacency_matrix(final_approx_k5)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>find_ranking_power_matrix(k6_weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cornell

Harvard

Penn

Princeton

Dartmouth

Yale

Brown

Columbia
</code></pre>
</div>
</div>
<p>Due to the increase in vectors being used as a basis for our approximation, we see less unpredictable patterns as variance is now regulated: our previous number 1 and 2 seeds after the midseason review have remained.</p>
<div id="f5ffd211" class="cell" data-execution_count="61">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Final approximation</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>sp.Matrix(final_approx_k5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="123">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0 &amp; 0 &amp; -1.0 &amp; 13.0 &amp; 2.0 &amp; 34.0 &amp; 41.0 &amp; -1.0\\-1.0 &amp; 0 &amp; 32.0 &amp; 2.0 &amp; 15.0 &amp; 1.0 &amp; 20.0 &amp; 1.0\\-2.0 &amp; 27.0 &amp; 0 &amp; 3.0 &amp; 14.0 &amp; -1.0 &amp; 1.0 &amp; 20.0\\20.0 &amp; 8.0 &amp; 1.0 &amp; 0 &amp; -3.0 &amp; 25.0 &amp; 1.0 &amp; 1.0\\2.0 &amp; 24.0 &amp; 15.0 &amp; -3.0 &amp; 0 &amp; 2.0 &amp; -2.0 &amp; 16.0\\31.0 &amp; -1.0 &amp; -1.0 &amp; 28.0 &amp; 3.0 &amp; 0 &amp; 13.0 &amp; 0\\23.0 &amp; 19.0 &amp; 1.0 &amp; -1.0 &amp; -2.0 &amp; 36.0 &amp; 0 &amp; 7.0\\2.0 &amp; 3.0 &amp; 11.0 &amp; 4.0 &amp; 7.0 &amp; -4.0 &amp; 5.0 &amp; 0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>We now compare this approximate final results with the true final results.</p>
<div id="b05d9838" class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>final_true <span class="op">=</span> pd.read_csv(<span class="st">'Ivy League Stats - Full Season.csv'</span>)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>final <span class="op">=</span> final_true.to_numpy()</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>final <span class="op">=</span> np.delete(final, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>sp.Matrix(final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="124">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0 &amp; 18 &amp; 17 &amp; 14 &amp; 25 &amp; 34 &amp; 41 &amp; 38\\23 &amp; 0 &amp; 31 &amp; 36 &amp; 17 &amp; 36 &amp; 21 &amp; 35\\9 &amp; 24 &amp; 0 &amp; 23 &amp; 23 &amp; 38 &amp; 30 &amp; 20\\21 &amp; 28 &amp; 21 &amp; 0 &amp; 31 &amp; 27 &amp; 14 &amp; 10\\23 &amp; 27 &amp; 20 &amp; 24 &amp; 0 &amp; 26 &amp; 23 &amp; 20\\31 &amp; 17 &amp; 13 &amp; 28 &amp; 30 &amp; 0 &amp; 14 &amp; 21\\23 &amp; 23 &amp; 14 &amp; 3 &amp; 8 &amp; 36 &amp; 0 &amp; 14\\24 &amp; 7 &amp; 9 &amp; 7 &amp; 17 &amp; 14 &amp; 29 &amp; 0\end{matrix}\right]\)</span></p>
</div>
</div>
<div id="57e8d79c" class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>final_weight <span class="op">=</span> weighted_adjacency_matrix(final)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>find_ranking_power_matrix(final_weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Yale

Dartmouth

Harvard

Cornell

Penn

Princeton

Columbia

Brown
</code></pre>
</div>
</div>
<p>As we can see, by our approximations we were only able to predict two of the top 4 teams. Moreover, we had both Yale and Dartmouth, the top 2 teams, as bottom 4 teams in our predictions. This misapproximation is likely due to both the midseason results we started with and the way we estimated our missing values.</p>
<div id="37896bd8" class="cell" data-execution_count="64">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>sp.pprint(teams)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>sp.Matrix(midseason)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[Harvard, Yale, Dartmouth, Princeton, Penn, Brown, Cornell, Columbia]</code></pre>
</div>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="126">
<p><span class="math inline">\(\displaystyle \left[\begin{matrix}0 &amp; 0 &amp; 0 &amp; 14.0 &amp; 0 &amp; 34.0 &amp; 41.0 &amp; 0\\0 &amp; 0 &amp; 31.0 &amp; 0 &amp; 17.0 &amp; 0 &amp; 21.0 &amp; 0\\0 &amp; 24.0 &amp; 0 &amp; 0 &amp; 23.0 &amp; 0 &amp; 0 &amp; 20.0\\21.0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 27.0 &amp; 0 &amp; 10.0\\0 &amp; 27.0 &amp; 20.0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 20.0\\31.0 &amp; 0 &amp; 0 &amp; 28.0 &amp; 0 &amp; 0 &amp; 14.0 &amp; 0\\23.0 &amp; 23.0 &amp; 0 &amp; 0 &amp; 0 &amp; 36.0 &amp; 0 &amp; 0\\0 &amp; 0 &amp; 9.0 &amp; 7.0 &amp; 17.0 &amp; 0 &amp; 0 &amp; 0\end{matrix}\right]\)</span></p>
</div>
</div>
<p>As seen in the graph, we can see that before the midseason review, Cornell had its three strongest performances all season. Thus, they were weighted higher in SVD approximations because they performed so well early. Meanwhile, Yale had 2 of its weakest performances scoring wise early. Thus, they were weighted less heavily in our approximation and is likely why we did not consider them as strong beforehand.</p>
<div class="comments">
<p>This is a very nice and creative approach. It’s well organized and you’ve explained your thinking well. I really like that you’ve sanity-checked your results against the power ranking techniques.</p>
<p>What you have done here is akin to an “image denoising”. You made a thoughtful choice for what to put in for the missing values; but we can think of them as being the true values plus some unknown “noise”. Then, if there is an underlying low-rank structure to the matrix, which the noise doesn’t follow, your approach should be able to predict the true values.</p>
<p>I would interpret the fact that your analysis wasn’t very successful in terms of its predictions as evidence that the structure of the data isn’t well-represented by a low-rank matrix.</p>
<p>I will note that this overall approach is not actually what the problem asked for. There, you were supposed to set up a directed incidence matrix A showing which teams were playing which team in every game before midseason, and then have the score spread as an output, and try to find a vector of strengths such that A * strengths = spread for the games which had already been played. Because this system would be inconsistent, you’d need to use least squares to find the best-fit for <span class="math inline">\(strengths\)</span>. Then, once you had the strengths, you’d use a bigger incidence matrix which included all the games to predict their results.</p>
<p>If I had much more time, I’d be curious to see the differences in these two approaches. The least squares approach also assumes a certain low-rank underlying structure, but perhaps it deals more elegantly with the missing values…</p>
<p>Anyways! Your work was great. Grade: E</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/KBurbank/stat24320/edit/main/submitted/projects_2/tandocalec.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/KBurbank/stat24320/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>