---
title: Homework 4
number-sections: true
section-divs: true
publish: false
due-date: Friday, Week 6
textbook-chapters: 3.4, 3.6, 4.2
publish-solutions-on: 2024-05-01
include-before-body: 
    - text: '**Reading: Chapters {{< meta textbook-chapters >}}**'
---

**Reading: Chapters {{< meta textbook-chapters >}}**

#
For the following matrices find the null space of $I-A$ and find state vectors with nonnegative entries that sum to 1 in the null space, if any. Are these matrices stable (yes/no)?

(a) $A=\left[\begin{array}{rrr}0.5 & 0 & 1 \\ 0.5 & 0.5 & 0 \\ 0 & 0.5 & 0\end{array}\right]$

(b) $A=\left[\begin{array}{ll}0 & 1 \\ 1 & 0\end{array}\right]$


::: solutions
Exercise 3.6.7
:::

#
Find bases for the row, column, and null space of each of the following matrices.
(a) $[2,0,-1]$
(b) $\left[\begin{array}{lllll}1 & 2 & 0 & 0 & 1 \\ 1 & 2 & 1 & 1 & 1 \\ 3 & 6 & 2 & 2 & 3\end{array}\right]$
(c) $\left[\begin{array}{ccccc}1 & 2 & 0 & 4 & 0 \\ 1 & 3 & 5 & 2 & 1 \\ 2 & 3 & -5 & 10 & 0 \\ 2 & 4 & 0 & 8 & 1\end{array}\right]$
(d) $\left[\begin{array}{rrr}2 & -3 & -1 \\ 0 & 2 & 0 \\ 2 & 4 & 1\end{array}\right]$

::: solutions
Exercise 3.6.5
:::

# 

 Find all possible linear combinations with value zero of the following sets of vectors and the dimension of the space spanned by them.

(a) $(0,1,1),(2,0,1),(2,2,3),(0,2,2)$ in $\mathbb{R}^{3}$.

(b) $x, x^{2}+x, x^{2}-x$ in $\mathcal{P}_{2}$.

(c) $(1,1,2,2),(0,2,0,2),(1,0,2,1),(2,1,4,4)$ in $\mathbb{R}^{4}$.

::: solutions
Exercise 3.6.7
:::

#

Let $A=\left[\begin{array}{lllll}0 & 1 & 0 & 1 & 2 \\ 1 & 0 & 2 & 1 & 2 \\ 2 & 2 & 4 & 4 & 8\end{array}\right]$. Use the column space algorithm on the matrix $[A I]$ to find a basis $B$ of $\mathcal{C}(A)$ and to expand it to a basis of $\mathbb{R}^{3}$.

::: solutions
Exercise 3.6.13
:::

#
 For the following orthogonal pairs $\mathbf{u}, \mathbf{v}$ and matrix $M=\left[\begin{array}{rrr}1 & 0 & -1 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{array}\right]$, determine whether $M \mathbf{u}$ and $M \mathbf{v}$ are orthogonal.
(a) $(2,1,1),(1,0,-2)$
(b) $(0,1,1),(1,-1,1)$
(c) $(3,1,-2),(1,3,3)$

::: solutions
4.2.7
:::

#

 Find equations for the following planes in $\mathbb{R}^{3}$.

(a) The plane containing the points $(1,1,2),(-1,3,2),(2,4,3)$.

(b) The plane containing the points $(-2,1,1)$ and $(0,1,2)$ and orthogonal to the plane $2 x-y+z=3$.

::: solutions
Exercise 4.2.9
:::

#

 Find equations for the following hyperplanes in $\mathbb{R}^{4}$.

(a) The plane parallel to the plane $2 x_{1}+x_{2}-3 x_{3}+x_{4}=2$ and containing the point $(2,1,1,3)$.

(b) The plane through the origin and orthogonal to the vector $(1,0,2,1)$.

::: solutions
Exercise 4.2.10
:::

#
 For each pair $A, \mathbf{b}$, solve the normal equations for the system $A \mathbf{x}=\mathbf{b}$ and find the residual vector and its norm. Are there any genuine solutions to the system?
(a) $\left[\begin{array}{ll}1 & 3 \\ 1 & 0\end{array}\right],\left[\begin{array}{l}1 \\ 3\end{array}\right]$
(b) $\left[\begin{array}{rr}2 & -2 \\ 1 & 1 \\ 3 & 1\end{array}\right],\left[\begin{array}{r}2 \\ -1 \\ 1\end{array}\right]$
(c) $\left[\begin{array}{rrr}0 & 2 & 2 \\ 1 & 1 & 0 \\ -1 & 1 & 2 \\ 1 & -2 & -3\end{array}\right],\left[\begin{array}{l}3 \\ 1 \\ 0 \\ 0\end{array}\right]$
::: solutions
Exercise 4.2.11
:::


#


 (Text retrieval) You are given the following term-by-document matrix, that is, a matrix whose $(i, j)$ th entry is the number of times term $t_{i}$ occurs in document $D_{j}$. Columns of this matrix are document vectors, as are queries. We measure the quality of a match between query and document by the cosine of the angle $\theta$ between the two vectors, larger cosine being better. Which of the following nine documents $D_{i}$ matches the query $(0,1,0,1,1)$ above the threshold value $\cos \theta \geq 0.5$ ? Which is the best match to the query?

|  | $D_{1}$ | $D_{2}$ | $D_{3}$ | $D_{4}$ | $D_{5}$ | $D_{6}$ | $D_{7}$ | $D_{8}$ | $D_{9}$ |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| $t_{1}$ | 1 | 1 | 2 | 0 | 1 | 0 | 1 | 0 | 1 |
| $t_{2}$ | 0 | 1 | 0 | 1 | 0 | 1 | 1 | 0 | 0 |
| $t_{3}$ | 0 | 2 | 0 | 2 | 0 | 1 | 0 | 1 | 1 |
| $t_{4}$ | 1 | 0 | 1 | 0 | 1 | 0 | 2 | 1 | 0 |
| $t_{5}$ | 1 | 2 | 1 | 0 | 0 | 1 | 0 | 0 | 1 |

::: solutions
Exercise 4.2.14
:::
