---
title: Homework 6
publish: false
due-date: Friday, Week 9
textbook-chapters: 5.1,
publish-solutions-on: 2024-05-10
---

#
Show that if the real matrix $A$ is orthogonally diagonalizable, then $A$ is symmetric.

::: solutions
5.4.13
:::

#
::: solutions
5.6.3
:::

 Use a technology tool to compute an orthonormal basis for the null space and column space of the following matrices with the SVD and Corollary 5.7. You will have to decide which nearly-zero terms are really zero.
(a) $\left[\begin{array}{rrr}1 & 1 & 3 \\ 0 & -1 & 0 \\ 1 & -2 & 2 \\ 3 & 0 & 2\end{array}\right]$

(b) $\left[\begin{array}{rrr}3 & 1 & 2 \\ 4 & 0 & 1 \\ -1 & 1 & 1\end{array}\right]$

(c) $\left[\begin{array}{ccccr}1 & 0 & 1 & 0 & -3 \\ 1 & 2 & 1 & -5 & 2 \\ 0 & 1 & 0 & -3 & 1 \\ 0 & 2 & -3 & 1 & 4\end{array}\right]$

#
::: solutions
5.6.4
:::

 Use the pseudoinverse to find a least squares solution $A \mathbf{x}=\mathbf{b}$, where $A$ is a matrix from Exercise 3 with corresponding right-hand side below.

(a) $(2,2,6,5)$

(b) $(2,3,1)$

(c) $(4,1,2,3)$

#

Use a technology tool to construct a $3 \times 10$ table whose $j$ th column is $A^{j} \mathbf{x}$, where $\mathbf{x}=(1,1,1)$ and $A=\left[\begin{array}{rrr}10 & 17 & 8 \\ -8 & -13 & -6 \\ 4 & 7 & 4\end{array}\right]$. What can you deduce about the eigenvalues of $A$ based on inspection of this table? Give reasons. Check your claims by finding the eigenvalues of $A$.

::: solutions

5.3.14

```{python}
import sympy as sp

A = sp.Matrix([[10, 17, 8], [-8, -13, -6], [4, 7, 4]])
display(A)
x = sp.Matrix([1, 1, 1])
ev1 = A.eigenvects()[0][2][0]
ev2 = A.eigenvects()[1][2][0]
ev3 = A.eigenvects()[2][2][0]
ev1, ev2, ev3
mytable = sp.Matrix([(A**j * x).T for j in range(1, 11)]).T
mytable
```

Largest eigenvalue must be greater than one because the numbers grow, and complex because they take two iterations to change sign. But the complex part probably comes in pairs which cancel each other.

:::

#


Compute the DTFT for the FIR filter $\mathbf{h}=\left\{\frac{1}{2}, \frac{1}{2}\right\}$ and confirm that $\mathbf{h}$ is a lowpass filter.


::: solutions
6.6.1
:::

#

Compute the DTFT for the FIR filter $\mathbf{h}=\left\{-\frac{1}{2}, \frac{1}{2}\right\}$ and confirm that $\mathbf{h}$ is a highpass filter.

::: solutions
6.6.2
:::

#
Compute the Fourier series for $x(t) \in C_{P W}^{1}[-\pi, \pi]$, where $x(t)=$ $t^{2} / \pi,-\pi \leq t \leq \pi$ and graph $x(t)$ and the partial Fourier sums with $N=3,6$.


::: solutions
6.6.3
:::

#


Compute the Fourier series for $x(t) \in C_{P W}^{1}[0,2 \pi]$, where $x(t)=$ $t^{3} / 6-1,0 \leq t<2 \pi$, and $x(2 \pi)=-1$ and graph results as in Exercise 3.

::: solutions
6.6.4
:::

